
----------------------------------LOCATION----------------------------------------

CREATE TABLE IF NOT EXISTS REGION (
CODE  VARCHAR (2)  NULL,
ID  VARCHAR (3)  PRIMARY KEY,
NAME  VARCHAR (50)  NULL,
NAME_AR  VARCHAR (50)  NULL
);

CREATE TABLE IF NOT EXISTS PROVINCE (
REGION_ID VARCHAR (3) NULL,
CODE VARCHAR (3) NULL,
ID VARCHAR (7) PRIMARY KEY,
NAME VARCHAR (50) NULL,
NAME_AR VARCHAR (50) NULL
);


CREATE TABLE IF NOT EXISTS CIRCLE (
REGION_ID VARCHAR (3) NOT NULL,
PROVINCE_ID VARCHAR (7) NULL,
CODE VARCHAR (3) NULL,
ID VARCHAR (15) PRIMARY KEY,
NAME VARCHAR (60) NULL,
NAME_AR VARCHAR (60) NULL
);

CREATE TABLE IF NOT EXISTS COMMUNE (
REGION_ID VARCHAR (3)  NULL,
PROVINCE_ID VARCHAR (7)  NULL,
CIRCLE_ID  VARCHAR (15) NULL,
CODE  VARCHAR (3) NULL,
ID  VARCHAR (20) PRIMARY KEY,
NAME  VARCHAR (50) NULL,
NAME_AR  VARCHAR (50) NULL,
IS_MUNICIPAL INT NULL,
IS_ARRONDISSMENT INT NULL,
IS_CENTRE INT NULL
);

CREATE TABLE IF NOT EXISTS PHONE_VERIFICATION  (
ID INT PRIMARY KEY,
PHONE_NUMBER  VARCHAR (50)  NULL,
VERIFICATION_CODE INT NULL,
EXPIRATION_TIME INT NULL
);

----------------------------------------SUBVENTION---------------------------------------

CREATE TABLE IF NOT EXISTS SUBVENTION_ACTOR_ROLE  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL
);

CREATE TABLE IF NOT EXISTS SUBVENTION_ACTOR  (
ID INT PRIMARY KEY,
FIRST_NAME  VARCHAR (50)  NULL,
LAST_NAME  VARCHAR (50)  NULL,
USERNAME  VARCHAR (50)  NULL,
HASH_PWD  VARCHAR (50)  NULL,
ROLE_ID INT NULL,
PHONE  VARCHAR (15)  NULL,
IS_ENABLED INT NULL
);

CREATE TABLE IF NOT EXISTS SUBVENTION_ACTOR_LOCATION  (
SUBVENTOR_ID INT NULL,
PROVINCE_ID VARCHAR (7) NULL
);



CREATE TABLE IF NOT EXISTS SUBVENTION_TYPE  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL
);


CREATE TABLE IF NOT EXISTS SUBVENTION  (
ID INT PRIMARY KEY,
REQUEST_ID INT NULL,
ACTOR_ID INT NULL,
VALUE INT NULL,
TYPE_ID INT NULL,
SUBVENTION_CODE  VARCHAR (20)  NULL,
SUBVENTION_MONTH INT NULL,
SUBVENTION_YEAR INT NULL,
CREATION_DATE  VARCHAR (20)  NULL,
IS_PROCESSED INT NULL
);


----------------------------------------REQUEST---------------------------------------

CREATE TABLE IF NOT EXISTS REQUEST  (
ID  INT PRIMARY KEY,
FULL_NAME  VARCHAR (50) NULL,
CIN  VARCHAR (50) NULL,
CIN_RECTO  VARCHAR (50) NULL,
CIN_VERSO  VARCHAR (50) NULL,
PHONE  VARCHAR (50) NULL,
ADDRESS  VARCHAR (50) NULL,
JOB_ADDRESS  VARCHAR (50) NULL,
JOB_TYPE  VARCHAR (50) NULL,
JOB_JUSTIFICATION  TEXT NULL,
REGION_ID VARCHAR (50) NULL,
PROVINCE_ID VARCHAR (50) NULL,
CIRCLE_ID VARCHAR (50) NULL,
COMMUNE_ID VARCHAR (50) NULL,
STATUS_ID INT  NULL,
ASSIGNED_AUTHORITY_ID  INT NULL,
PROCESSED_BY_AUTHORITY_ID  INT NULL,
PROCESSED_BY_CHIEF_AUTHORITY_ID  INT NULL,
REJECT_REASON  VARCHAR (200) NULL,
STATUS_UPDATE_DATE VARCHAR (50) NULL,
CREATION_DATE VARCHAR (50) NULL,
FAMILY_STATUS_ID  INT NULL,
CHILD_NUMBER INT NULL,
HAS_RAMED VARCHAR (50) NULL,
RAMED_CARD_NUMBER VARCHAR (50) NULL
);



CREATE TABLE IF NOT EXISTS REQUEST_UPDATE_EVENT  (
REQUEST_ID INT NULL,
PREVIOUS_STATUS_ID INT NULL,
NEW_STATUS_ID INT NULL,
ACTOR_TYPE_ID INT NULL,
ACTOR_ID INT NULL,
UPDATE_DATE  VARCHAR (50)  NULL
);


CREATE TABLE IF NOT EXISTS REQUEST_STATUS  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL
);




CREATE TABLE IF NOT EXISTS REQUEST_ACTOR_TYPE  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL
);

CREATE TABLE IF NOT EXISTS FAMILY_STATUS  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL
);


CREATE TABLE IF NOT EXISTS REQUEST_REJECT_REASON  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL,
DESCRIPTION  VARCHAR (500)  NULL
);

----------------------------------AUTHORITY----------------------------------------

CREATE TABLE IF NOT EXISTS CAIDAT  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL,
NAME_AR  VARCHAR (50)  NULL,
DESCRIPTION  VARCHAR (500)  NULL,
CREATION_DATE  VARCHAR (50)  NULL,
LATITUDE FLOAT NULL,
LONGITUDE FLOAT NULL
);


CREATE TABLE IF NOT EXISTS REQUEST_ASSIGNEMENT  (
AUTHORITY_ID INT NULL,
REQUEST_ID INT NULL,
CHIEF_AUTHORITY_ID INT NULL,
ASSIGNEMENT_DATE VARCHAR(22) NULL,
IS_VIEWED INT NULL
);



CREATE TABLE IF NOT EXISTS CAIDAT_COMMUNE_ASSOCIATION  (
COMMUNE_ID VARCHAR(20) NULL,
CAIDAT_ID INT NULL
);

CREATE TABLE IF NOT EXISTS AUTHORITY_ROLE  (
ID INT PRIMARY KEY,
NAME  VARCHAR (50)  NULL
);


CREATE TABLE IF NOT EXISTS AUTHORITY  (
ID INT PRIMARY KEY,
FULL_NAME  VARCHAR (50)  NULL,
PHONE INT NULL,
HASH_PWD  VARCHAR (50)  NULL,
CAIDAT_ID INT NULL,
ROLE_ID INT NULL,
CHIEF_AUTHORITY_ID INT NULL,
IS_ENABLED INT NULL
);



ALTER TABLE CAIDAT_COMMUNE_ASSOCIATION
    ADD CONSTRAINT CAIDAT_COMMUNE_ASSOCIATION_COMMUNE_ID FOREIGN KEY (COMMUNE_ID) REFERENCES COMMUNE (ID),
    ADD CONSTRAINT CAIDAT_COMMUNE_ASSOCIATION_CAIDAT_ID FOREIGN KEY (CAIDAT_ID) REFERENCES CAIDAT (ID);


ALTER TABLE PROVINCE
    ADD CONSTRAINT PROVINCE_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES REGION (ID);


ALTER TABLE CIRCLE
    ADD CONSTRAINT CIRCLE_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES REGION (ID),
    ADD CONSTRAINT CIRCLE_PROVINCE_ID FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE (ID);


ALTER TABLE COMMUNE
    ADD CONSTRAINT COMMUNE_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES REGION (ID),
    ADD CONSTRAINT COMMUNE_PROVINCE_ID FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE (ID),
    ADD CONSTRAINT COMMUNE_CIRCLE_ID FOREIGN KEY (CIRCLE_ID) REFERENCES CIRCLE (ID);


ALTER TABLE SUBVENTION_ACTOR
    ADD CONSTRAINT SUBVENTION_ACTOR_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES SUBVENTION_ACTOR_ROLE (ID);

ALTER TABLE SUBVENTION_ACTOR_LOCATION
    ADD CONSTRAINT SUBVENTION_ACTOR_LOCATION_SUBVENTOR_ID FOREIGN KEY (SUBVENTOR_ID) REFERENCES SUBVENTION_ACTOR (ID),
    ADD CONSTRAINT SUBVENTION_ACTOR_LOCATION_PROVINCE_ID FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE (ID);



ALTER TABLE SUBVENTION
    ADD CONSTRAINT SUBVENTION_REQUEST_ID FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST (ID),
    ADD CONSTRAINT SUBVENTION_ACTOR_ID FOREIGN KEY (ACTOR_ID) REFERENCES SUBVENTION_ACTOR (ID),
    ADD CONSTRAINT SUBVENTION_TYPE_ID FOREIGN KEY (TYPE_ID) REFERENCES SUBVENTION_TYPE (ID);


ALTER TABLE REQUEST
    ADD CONSTRAINT REQUEST_REGION_ID FOREIGN KEY (REGION_ID) REFERENCES REGION (ID),
    ADD CONSTRAINT REQUEST_PROVINCE_ID FOREIGN KEY (PROVINCE_ID) REFERENCES PROVINCE (ID),
    ADD CONSTRAINT REQUEST_CIRCLE_ID FOREIGN KEY (CIRCLE_ID) REFERENCES CIRCLE (ID),
    ADD CONSTRAINT REQUEST_COMMUNE_ID FOREIGN KEY (COMMUNE_ID) REFERENCES COMMUNE (ID),
    ADD CONSTRAINT REQUEST_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES REQUEST_STATUS (ID),
    ADD CONSTRAINT REQUEST_ASSIGNED_AUTHORITY_ID FOREIGN KEY (ASSIGNED_AUTHORITY_ID) REFERENCES AUTHORITY (ID),
    ADD CONSTRAINT REQUEST_PROCESSED_BY_AUTHORITY_ID FOREIGN KEY (PROCESSED_BY_AUTHORITY_ID) REFERENCES AUTHORITY (ID),
    ADD CONSTRAINT REQUEST_PROCESSED_BY_CHIEF_AUTHORITY_ID FOREIGN KEY (PROCESSED_BY_CHIEF_AUTHORITY_ID) REFERENCES AUTHORITY (ID),
    ADD CONSTRAINT REQUEST_FAMILY_STATUS_ID FOREIGN KEY (FAMILY_STATUS_ID) REFERENCES FAMILY_STATUS (ID);

ALTER TABLE REQUEST_UPDATE_EVENT
    ADD CONSTRAINT REQUEST_UPDATE_EVENT_PREVIOUS_STATUS_ID FOREIGN KEY (PREVIOUS_STATUS_ID) REFERENCES REQUEST_STATUS (ID),
    ADD CONSTRAINT REQUEST_UPDATE_EVENT_NEW_STATUS_ID FOREIGN KEY (NEW_STATUS_ID) REFERENCES REQUEST_STATUS (ID),
    ADD CONSTRAINT REQUEST_UPDATE_EVENT_ACTOR_ID FOREIGN KEY (ACTOR_ID) REFERENCES AUTHORITY (ID),
    ADD CONSTRAINT REQUEST_UPDATE_EVENT_ACTOR_TYPE_ID FOREIGN KEY (ACTOR_TYPE_ID) REFERENCES AUTHORITY_ROLE (ID);



ALTER TABLE REQUEST_ASSIGNEMENT
    ADD CONSTRAINT REQUEST_ASSIGNEMENT_AUTHORITY_ID FOREIGN KEY (AUTHORITY_ID) REFERENCES AUTHORITY (ID),
    ADD CONSTRAINT REQUEST_ASSIGNEMENT_CHIEF_AUTHORITY_ID FOREIGN KEY (CHIEF_AUTHORITY_ID) REFERENCES AUTHORITY (ID),
    ADD CONSTRAINT REQUEST_ASSIGNEMENT_REQUEST_ID FOREIGN KEY (REQUEST_ID) REFERENCES REQUEST (ID);

ALTER TABLE AUTHORITY
    ADD CONSTRAINT AUTHORITY_CAIDAT_ID FOREIGN KEY (CAIDAT_ID) REFERENCES CAIDAT (ID),
    ADD CONSTRAINT AUTHORITY_ROLE_ID FOREIGN KEY (ROLE_ID) REFERENCES AUTHORITY_ROLE (ID),
    ADD CONSTRAINT AUTHORITY_CHIEF_AUTHORITY_ID FOREIGN KEY (CHIEF_AUTHORITY_ID) REFERENCES AUTHORITY (ID);


